Frontend sprint 1
ro-msg-spring-training/event-management pull request #37
Opened 2020-08-21 06:30 UTC by teodoraalexandra

2020-08-21 10:10 UTC, calincara requested changes
I did review for part of the code. Will continue next week.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/en/translation.json
> +    "successMessage": "Succesful login",
Succes**s**ful with 2 's'

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/en/translation.json
> +    "loginSuccess": "Succesful login",
Succes**s**ful with 2 's'

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/en/translation.json
> +    "overviewStartDate": "StartDate",
_Start Date_ instead of _StartDate_

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/en/translation.json
> +    "overviewEndDate": "EndDate",
_End Date_ instead of _EndDate_

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/en/translation.json
> +    "overviewStartTime": "StartTime",
_Start Time_ instead of _StartTime_

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/en/translation.json
> +    "overviewEndTime": "EndTime",
_End Time_ instead of _EndTime_

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/en/translation.json
> +    "selectedLocationMessage": " Selected location for the event",
Is that empty space before the 'Selected' needed?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/ro/translation.json
> +        "createNewEventButton": "Crează eveniment nou",
_Creează_ in loc de _Crează_

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/ro/translation.json
> +        "passwordError": "Cerințe: min. 8 caractere, litere mari și un număr.",
Putin neclar: cate litere mari trebuie puse?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/ro/translation.json
> +        "passwordError": "Cerințe: min. 8 caractere, litere mari și un număr.",
Same as above, cate litere mari trebuie sa introduc?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/public/locales/ro/translation.json
> +    "welcome": {
Toata sectiunea de _welcome_ e scrisa fara diacritice.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/App.css
> +/* .App-logo {
Remove commented CSS

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/actions/EventsPageActions.tsx
> +export const FETCH_CUSTOM_EVENTS_ERROR = 'FETCH_EVENTS_CUSTOM_ERROR'
Uhm, the words _EVENTS_ and _CUSTOM_ are interchanged in constant vs string value. Was this working? :) Best is to copy-paste the values, to make sure that they're exactly the same.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/actions/EventsPageActions.tsx
> +export const FETCH_CUSTOM_EVENTS_ERROR_HOME = 'FETCH_EVENTS_CUSTOM_ERROR_HOME'
Same here, the words _EVENTS_ and _CUSTOM_ are interchanged

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    if (filters.title !== '' && filters.title !== undefined) {
Can be changed to `if (filters.title)`. Same for all the checks below.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +        filtersToSend['title'] = filters.title
Use JavaScript dot notation instead of bracket notation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors

_filtersToSend.title_ instead of _filtersToSend['title']_

Same for all the cases below.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    let filtersToSend: any = {}
Maybe add a type for this object? (If it doesn't created issues with the API call later)

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    const limitToSend = computeLimit()
Add ; at the end of all expressions. Same for all the code below.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    url.search += "&"
Add ; Same for all the code below.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    // Hardcoded
Remove commented code.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    return 5;
Is this work in progress? What if there are 10 pages of events?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/HeaderEventCrudAPI.tsx
> +//TODO modify links
Remove Todo comment if not valid. If valid, fix the issue.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/HeaderEventCrudAPI.tsx
> +  const pictures = { picturesToSave: newAddedImagesIds, picturesToDelete: imagesToDelete }
Add ;

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/HeaderEventCrudAPI.tsx
> +  }).then(response => response.json(),) // return string[]
Add ; and remove comment if not needed anymore

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/HeaderEventCrudAPI.tsx
> +    images[indexImage].url = `${s3URL}/${images[indexImage].id}`
Add ;

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/HeaderEventCrudAPI.tsx
> +  return images.filter(img => img.deleted === undefined).map(img => img.url)
Add ;

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Images.tsx
> +export default Images;
Unused file?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Location.tsx
> +export default Location;
Unused file?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Main.tsx
> +import { Container } from '@material-ui/core';
Unused import.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Main.tsx
> +//TODO: i18n for all story admin page
Is this Todo still valid? Remove if not, or solve.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Main.tsx
> +                            render={(props: any) => <EventDetails match={props.match} admin={true} />} />
Why did you use PrivateRoute above, but not here as well?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Main.tsx
> +    if (width <= 600) {
This whole approach is wrong.
If you minimize the window, you get re-directed to _/login_ page.
Also the two `return `statements are the same.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/PrivateRoute.tsx
> +        })
Add ;

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Routes.tsx
> +        <hr /> */}
Remove unused code

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Routes.tsx
> +          <Route path="/changepasswordconfirmation" component={ChangePasswordConfirm}></Route>
Would be more readable to have camel case notation for the URLs.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/Tickets.tsx
> +import React from 'react';
Unused file?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/YellowCheckbox.tsx
> +    checked: {},
Shouldn't this be a boolean type?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +  admin: boolean,
Should be renamed to _isAdmin_

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    limit['limit'] = 2;
Use JavaScript dot notation instead of bracket notation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors

`filtersToSend.title` instead of `filtersToSend['title']`

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    let limit: any = {}
Add a type for this object.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +  resetStoreF: () => void,
What does `F` stand for, and why don't name the variables without it?

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +  let newEvent = match.path === "/admin/newEvent" ? true : false;
Can be simplified to `let newEvent = match.path === "/admin/newEvent";`

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +  const formValid = (event: EventCrud, errors: EventFormErrors): boolean => {
Rename to `isFormValid`

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +  value: any;
Try to avoid type `any` in general, unless really needed.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +  const handleChange = (event: React.ChangeEvent<{}>, newValue: number) => {
Rename to `handleTabChange`, to better illustrate what the function does.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +const useStyles2 = makeStyles({
For the whole file: try to be more descriptive when naming stuff.
`classes.buttonStyle2` and `classes.buttonStyle3` don't say much.

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +  admin: boolean,
Rename to `isAdmin`

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +  handleSave: any,
Rename to `handleEventDelete` and `handleEventSave`

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +    : null
End statement with `;`. Same below

2020-08-21 10:10 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +  const bigWindow = <Grid container spacing={2} className={classes2.grid} direction="row" justify="space-between" alignItems="center">
You're using two different components, `bigWindow` and `smallWindow`. This is not really ok and should be changed. Check how Material UI Grid works, you should be able to control the "amount" of space a component takes from those `sm`, `xs`, `md`, etc. properties which Grid takes.

2020-08-21 11:26 UTC, teodoraalexandra commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    return 5;
It is in progress, yes. I'm waiting for the backend to give me the url for last page :))

2020-08-21 13:36 UTC, ciubucalexandru reviewed
Partial review. Will continue next week.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/actions/EventsPageActions.tsx
> +export const FETCH_CUSTOM_EVENTS_ERROR = 'FETCH_EVENTS_CUSTOM_ERROR'
It would only cause problems if the string is identical to another one among the actions. But as you said, it's better to just copy paste the value, to make sure there are no confusions.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/actions/EventsPageActions.tsx
> +export const prevPage = (filters: EventFilters, sort: EventSort) => {
I see that your actions files aren't really consistent. There are files where you only created the functions for the actions and then there are files where you also created types (classes, I think) for them. As I suggested even during the training period, use types as much as possible. We would have used JS instead of TS if we wanted to dodge types.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/actions/LocationActions.tsx
> +import { LocationType } from "../types/LocationType";
This would be the model for the actions files.
Benefits:
 - Typing of actions
 - Usage of union types ( https://codingblast.com/typescript-union-types-type-guards-type-aliases/ ) which will be useful when using the action types in the reducer 'switch' statement
 - Usage of enums for a better grouping of actions. Read more here https://medium.com/razroo/typescript-enums-v-constants-576536163cc9. In our case, we don't need string literals for action names, so we can use enums without any drawbacks.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/Api.tsx
> +}
Add new line

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/Api.tsx
> +export const token = localStorage.getItem("idToken")
https://dev.to/rdegges/please-stop-using-local-storage-1i04

We need to talk about this a little bit. Contact me on monday so we can find a more secure option instead of localStorage.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    if (filters.subtitle !== '' && filters.subtitle !== undefined) {
These ones where you test for '' and undefined can be limited to:
`if (filters.subtitle)`

https://medium.com/coding-at-dawn/what-are-falsy-values-in-javascript-ca0faa34feb4

Alternatively, you can find a clever ternary statement or a short-circuit evaluation of '&&' for all these 'if' statements.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +}
Add new line

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    // UNCOMMENT THIS ONLY IF ALL URLS ARE RIGHT
Ok

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/EventsServiceAPI.tsx
> +    url.search = new URLSearchParams(filtersToSend).toString();
Instead of manually appending strings, you can iterate over an object containing all query parameters using 'map' and append via 'join'. Not mandatory, but more elegant.
https://github.com/github/fetch/issues/256#issuecomment-241613757

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/FetchWrapper.tsx
> +}
Add new line

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/HeaderEventCrudAPI.tsx
> +      'Authorization': `Bearer ${token}`
Alternate use of single and double quotes for declaring strings. Please choose one and stick with it, preferably single quotes.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/api/LocationUrl.tsx
> +const locationUrl = "";
What is this used for?

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/Main.tsx
> +export default Main
Add new line

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/Main.tsx
> +            <div>
Useless div probably. Use fragments

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/Main.tsx
> +                        <Route exact path='/admin/events/:id'
As a rule, you usually put the more explicit paths first. Namely lines 50 and 52 should be interchanged.

How react router does the routing process is the following: it takes the list of routes in the Switch component and in the order you declared them, tries to match the route that was accessed to a component. Namely, if it looks for a component for route '/admin/events' and in the switch statement it finds the Route declared with path '/admin' first, it will match to it and never continue with the next ones.

Why it works in your case: you used the 'exact' prop for the Route component.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/PrivateRoute.tsx
> +export class PrivateRoute extends React.Component<any, any> {
Maybe try and set a type for these props and state.
Props may be a little tricky, but the state is surely declared by you.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/PrivateRoute.tsx
> +          isAdmin: user.signInUserSession.accessToken.payload['cognito:groups'].includes('ROLE_ADMIN')
Just to avoid typos, try and put all possible user roles in a separate type. (I would choose an enum for it)

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/PrivateRoute.tsx
> +    // return null when escapse component, it will no longer hold any data in memory
I'm pretty sure that React does this process automatically and there's no need to specifically return a null value on unmounting. If you consider otherwise, we can talk about it.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/PrivateRoute.tsx
> +          (this.state.isAuthenticated ?
Try to make a better indentation for this part, since it is kinda hard to understand which statement is on which level of the ternary operators.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/Routes.tsx
> +          <Route path="/changepasswordconfirmation" component={ChangePasswordConfirm}></Route>
I would actually recommand to use hyphens.

https://www.woorank.com/en/blog/underscores-in-urls-why-are-they-not-recommended

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/YellowCheckbox.tsx
> +  })(Checkbox);
Add new line

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/AlertDialog.tsx
> +    <div>
You can probably use React Fragments here.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +const useStyles = makeStyles({
Move to css as much of the styles as you can.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +    if (!(new Date(event.startDate) > new Date(event.endDate)) &&
Instead of calling `new Date(event...)` store these values into variables inside this fuction, before the if statement.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +  const verifyErrorMessages = (errors: EventFormErrors): boolean => {
You can probably mix this function with the 'verifyNullFields' one, because they seem to be doing almost the same thing and they are called from the same place.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/EventDetails.tsx
> +  let title = newEvent === false ? fetchEvent.event.title : t("welcome.newEventTitle");
Reduce `newEvent === false` to simply `newEvent`

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +const useStyles = makeStyles((theme: Theme) => ({
Could probably move this to css. I understand the problem with the theme object being used here. We would need to have a discussion regarding this.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +function TabPanel(props: TabPanelProps) {
Please move this component to a different file. You already have the stepper here.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +  overviewComponent: any,
They're not 'any', they're React components, or nodes.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +  const iconTab = <>
Could probably move these to different files as well.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +      {matches ? smallWindow : bigWindow}
This is not a good way of making a responsive application in this case. Namely because you have the Grid layout of Material UI that would do this job for you. You actually use it here but not well. Please consult this link for more info.

https://medium.com/better-programming/the-true-beauty-of-material-ui-d76fa3dc0dd4

From "Material-UI Docs, Nested Grids, and Components" downwards should be the info you need.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +    margin: '0px',
No need to specify 'px' when setting the value to 0.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +const useStyles2 = makeStyles({
Can be easily moved to css.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +  const classes2 = useStyles2();
Rename these as well, as Calin instructed above.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +      <Button variant="contained" className={`${classes.buttonStyle2} ${classes.buttonStyle3}`} onClick={handleDelete}> {t("welcome.headerCRUDCancel")} </Button> :
You can restrict the ternary operator for the HTML of the button only, namely:
`<Button variant="contained" className={`${classes.buttonStyle2} ${classes.buttonStyle3}`} onClick={handleDelete}> t("welcome.newEventTitle") ? {t("welcome.headerCRUDCancel")} : {t("welcome.headerCRUDDelete")}</Button>`

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +  const cancelButton = admin === true ?
No need to test for `admin === true ?`, a simple `admin ?` will do the trick.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudSmart.tsx
> +    <>
No need for fragments here, just return the dumb component.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudSmart.tsx
> +  let handleSave = (): void => {
No need to create new local functions here, just use the ones in the props.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/imagesSection/ImagesSectionDumb.tsx
> +  const [images, setImages] = useState<EventImage[]>(eventImages);
Remove all states from the dumb components. Move them to the smart version. The dumb component is strictly presentational, aka it should not:
   - Have any state
   - Do heavy computations and logical operations

Move all of that to the Smart one. Yes, you can connect your smart component to Redux and STILL have local states.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/imagesSection/ImagesSectionDumb.tsx
> +  return (
Probably could split this JSX into multiple components.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/Map.tsx
> +  return (
This JSX is way too huge. Split it in multiple smaller components.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/Map.tsx
> +import React, { useEffect, useState } from "react";
Looks like a good place to apply the Smart / Dumb thinking.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/SearchBar.tsx
> +  const renderSuggestions = () => {
They deserve a separate component.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/SearchBar.tsx
> +  setSearchValue: any;
Please add types.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/Map.tsx
> +  setlocationStatus: any;
Please add types.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/Map.tsx
> +  const [searchValue, setsearchValue] = useState("");
You could probably add the search value to the redux state and connect the Search Bar component to redux in order to retrieve it. Consider this if you ever need to access the search value from a lot of places.

2020-08-21 13:36 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/Map.tsx
> +        <SearchBar
As I mentioned in multiple places before and after, you could reduce the number of props you need to pass to this by connecting it to redux.

2020-08-21 13:40 UTC, ciubucalexandru commented
@IonutCosmina @Ioniqe @teodoraalexandra @teofanaenachioiu @juliaiakab Va dau si tag sa primiti notificari cand mai facem.

2020-08-22 18:46 UTC, calincara reviewed
Code review - part 2.

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewDumb.tsx
> +const YellowCheckbox = withStyles({
Could you re-use the component defined in `/src/components/YellowCheckbox.tsx` ?

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewDumb.tsx
> +            <Grid item xl={4} lg={4} sm={8} xs={11}>
`title`, `subtitle` and `maxPeople` grid components are almost identical. See if you can extract them to a single, reusable, dumb component which takes some props like `defaultValue`, `name` and so on, and re-use that component here to reduce the number of code lines.

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewDumb.tsx
> +  return (
JSX is too big and should be split into multiple components. Even if you have to create a separate component for each form item. Maybe you can also reuse some of them.

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewSmart.tsx
> +  const currDate = dateAndTime[0];
Whoa. Not sure what you were trying to do here, but JavaScript Date offers a lot of functionalities, I'm sure there's something useful you can find in there. Check here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewSmart.tsx
> +    switch (name) {
You can delete the whole switch and just say `newEvent[name] = value;`. TypeScript will complain, so you'll need to change the code at lie 44 as well to something like `const name = e.target.name as string;`

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewSmart.tsx
> +        break;
Same comment here as above.

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewSmart.tsx
> +      case "startDate":
For this and all the case statements below: 
- add ; at the end of all statements/line ends
- see if you can extract them to some generic function and reuse it - it's a lot of code which looks **very** similar. If making it generic is not possible, at least extract each case to a separate function and name them something like `isFistDayBeforeLastDay`, `isLastDayAfterFirstDay`, etc. and another function which sets the error message to your `newFormErrors` object.

2020-08-22 18:46 UTC, calincara commented on event-management-frontend/src/components/eventListPage/filterSection/FilterSectionDumb.tsx
> +import React, { FormEvent, KeyboardEvent } from 'react';
File and JSX is too large, should be split into smaller (maybe some generic) components. For example, Title, Subtitle and Location TextFields are almost identical, same with StartDate and EndDate, StartHour and EndHour.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/Stepper.tsx
> +export default Stepper;
Add new line

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/headerEditAndDelete/HeaderCrudDumb.tsx
> +  handleSave: any,
Also add types

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/locationSection/SearchBar.tsx
> +    sublocations: never[];
I'm pretty sure this is not a good place for using the 'never' type. Please consult this link and reconsider if needed.
https://mariusschulz.com/articles/the-never-type-in-typescript

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventCreateOrEdit/overviewSection/OverviewSmart.tsx
> +  setDialogDescription: any,
Please add types.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/filterSection/FilterSectionSmart.tsx
> +        filters.title = title
Please do not try to change the props object this way. You should never change props from a child component directly. Use callback functions instead.

In this case, you will probably need to dispatch an action for each field you change. Aka, when the title is changed, dispatch an action 'changeTitle' that will simply modify the value of the title in the Redux store.

UPDATE: I see that you already have something like that. So in your case, the best option would be to:
 - create a copy of the filters in this component ('newFilters') 
 - change the newFilters object on updating something ('newFilter.title = title')
 - dispatch the updateFilters action with the newFilter object as parameter

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsDumb.tsx
> +const StyledTableCell = withStyles((theme: Theme) =>
Move styles to css.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsDumb.tsx
> +const StyledTableRow = withStyles((theme: Theme) =>
This one as well.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsDumb.tsx
> +export default EventDetailsDumb
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsDumb.tsx
> +    const id = props.id;
Do not create local copies of props. There's no need for it. Use destructuring instead, in the function definition.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsMobileDumb.tsx
> +const StyledTableCell = withStyles((theme: Theme) =>
Move styles to css.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsMobileDumb.tsx
> +    const id = props.id;
As above.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsMobileDumb.tsx
> +const StyledTableRow = withStyles((theme: Theme) =>
This one as well.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventDetailsMobileDumb.tsx
> +export default EventDetailsMobileDumb
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListDumb.tsx
> +    eventsDetails: any[];
Please add types.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListDumb.tsx
> +    const eventsDetails = props.eventsDetails;
As above, do not create other variables just to point to already existing props. Use destructuring.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListDumb.tsx
> +        function updateSize() {
You already have the setWidth function, no need to create a new one for this.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListDumb.tsx
> +    useLayoutEffect(() => {
This is not a good way of making a responsive application in this case. Namely because you have the Grid layout of Material UI that would do this job for you. You actually use it here but not well. Please consult this link for more info.

https://medium.com/better-programming/the-true-beauty-of-material-ui-d76fa3dc0dd4

From "Material-UI Docs, Nested Grids, and Components" downwards should be the info you need.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListDumb.tsx
> +    if (width <= 600) {
Again, make it responsive using the Grid layout.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListDumb.tsx
> +    if (width <= 600) {
Also, this JSX is way too huge. Split it into smaller components.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListDumb.tsx
> +export default EventListDumb;
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListSmart.tsx
> +        // if (this.props.isLoading) {
Remove commented area.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListSmart.tsx
> +                //this.props.sortEvents(sortParams, this.props.page);
Remove else

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListSmart.tsx
> +                console.log("First page")
Remove console.log statements.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListSmart.tsx
> +        const eventDetails = events
Again, discard this logic. Please use the Grid layout to make responsive screens.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/eventListPage/listSection/EventListSmart.tsx
> +export default connect(mapStateToProps, { fetchAllEvents, sortEvents, prevPage, nextPage, fetchCustomEvents, updateSortCriteria, incrementPage, decrementPage })(EventListSmart)
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/header/Header.tsx
> +export default Header
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/Home.tsx
> +export default Home
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/Home.tsx
> +        <br />
Avoid using br's as much as possible.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventDetailsDumb.tsx
> +const useStyles = makeStyles({
Move styles to css.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventDetailsDumb.tsx
> +    const subtitle = props.subtitle;
Avoid creating new constants for already accessible props.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventDetailsDumb.tsx
> +export default HomeEventDetailsDumb
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListDumb.tsx
> +    const eventsDetails = props.eventsDetails;
Variables for props.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListDumb.tsx
> +    useLayoutEffect(() => {
Again, this way of making the app reactive is not optimal in your case. Use the Grid.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListDumb.tsx
> +                    <br /><br /><br /><br /><br /><CircularProgress />
Br's again. Check if you can replace them with a margin prop or something similar.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListDumb.tsx
> +export default HomeEventListDumb;
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListSmart.tsx
> +        decrementPageHome })(HomeEventListSmart)
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListDumb.tsx
> +    const [width, setWidth] = useState(window.innerWidth);
Move all state to the smart component.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListDumb.tsx
> +    const [width, setWidth] = useState(window.innerWidth);
But you won't need this state anymore, if you use the Grid correctly.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/homePage/HomeEventListSmart.tsx
> +    { fetchAllEventsHome,
Move these dispatch actions to a mapDispatchToProps function / object.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/ForgotPasswordVerification.tsx
> +  return (
Kind of a big JSX. Could try splitting it into some smaller ones.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/Login.tsx
> +      history.push('/admin/')
Could use the <Redirect ...> component for redirecting in some cases (it is in the React Router package).

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/Login.tsx
> +  return (
Also kind of a big JSX.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/RegistrationPage.tsx
> +  return (
Big JSX.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/RegistrationPage.tsx
> +  const [firstName, setFirstName] = useState("");
You have A LOT of states here. Please consider creating a redux store for this component.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/SuccessMessage.tsx
> +  if (props.success) {
`return (props.success ? <Alert ...  > ... </Alert> : null)`
Looks easier to comprehend.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/model/Event.tsx
> +export default Event;
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/model/EventFilters.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/model/EventFormErrors.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/model/EventImage.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/model/EventSort.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/model/MobileEvent.tsx
> +export default MobileEvent;
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/reducers/EventsPageReducers.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/reducers/HeaderEventCrudReducer.tsx
> +export default HeaderReducer
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/reducers/rootReducer.tsx
> +})
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/sagas/EventsPageSaga.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/sagas/EventsPageSaga.tsx
> +    yield delay(1000);
I don't think you really need this delay. Or even to catch these actions just to add a delay. Contact me if you consider otherwise.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/sagas/EventsPageSaga.tsx
> +    yield put(fetchCustomEventsRequest())
No need to dispatch a new request here. You can basically catch the FETCH_HOME_EVENTS request in the reducer and set the loading flag through it. Applies to more actions in this reducer.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/sagas/HeaderEventCrudSaga.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/sagas/rootSaga.tsx
> +        watchFetchFilteredEventsAsync(),
Please keep the names consistent. You've got two naming conventions here.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/services/ImagesService.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/store/store.tsx
> +export interface AppState {
Your app state seems pretty 'thin'. I think you have more than 3 pages that would need a state. Login, register, etc. I think I mentioned above in some comments that some of these app screens deserve a Redux store.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/styles/CommonStyles.tsx
> +export { useStyles }
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/styles/ImagesSectionStyles.tsx
> +})
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/styles/eventListStyles.tsx
> +});
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/utils/CompareUtilsForOverview.tsx
> +}
Add new line.

2020-08-24 09:03 UTC, ciubucalexandru commented on event-management-frontend/src/types/SublocationType.tsx
> +export interface SublocationType {
General comment about model / dto types: you don't need to have separate files for all of them. You can have two files (or more): model.ts, dto.ts or something like that.

2020-08-24 09:53 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/Login.tsx
> +import React, { useState } from "react";
I would prefer if all the logic of this component was written using Redux and Redux Saga. You have some side effects implemeed here, that would be more logically correct if they were done using saga.

2020-08-24 09:53 UTC, ciubucalexandru commented on event-management-frontend/src/components/loginRegisterPages/RegistrationPage.tsx
> +import React, { useState } from "react";
I would prefer if all the logic of this component was written using Redux and Redux Saga. You have some side effects implemeed here, that would be more logically correct if they were done using saga.

2020-08-24 10:10 UTC, ciubucalexandru commented on event-management-frontend/src/api/FetchWrapper.tsx
> +    .catch(err => console.log('Current session error', err));
Remove console logs.

2020-08-24 10:10 UTC, ciubucalexandru commented on event-management-frontend/src/components/header/AppBarCollapse.tsx
> +export default AppBarCollapse;
Add new line.

2020-08-27 08:35 UTC, merged